# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dawid/Projects/cmake_testing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dawid/Projects/cmake_testing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawid/Projects/cmake_testing/CMakeFiles /home/dawid/Projects/cmake_testing/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dawid/Projects/cmake_testing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_library

# Build rule for target.
test_library: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_library
.PHONY : test_library

# fast build rule for target.
test_library/fast:
	$(MAKE) -f CMakeFiles/test_library.dir/build.make CMakeFiles/test_library.dir/build
.PHONY : test_library/fast

#=============================================================================
# Target rules for targets named cmake_testing

# Build rule for target.
cmake_testing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cmake_testing
.PHONY : cmake_testing

# fast build rule for target.
cmake_testing/fast:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/build
.PHONY : cmake_testing/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/main.cpp.s
.PHONY : main.cpp.s

src/calc.o: src/calc.cpp.o

.PHONY : src/calc.o

# target to build an object file
src/calc.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/src/calc.cpp.o
.PHONY : src/calc.cpp.o

src/calc.i: src/calc.cpp.i

.PHONY : src/calc.i

# target to preprocess a source file
src/calc.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/src/calc.cpp.i
.PHONY : src/calc.cpp.i

src/calc.s: src/calc.cpp.s

.PHONY : src/calc.s

# target to generate assembly for a file
src/calc.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/src/calc.cpp.s
.PHONY : src/calc.cpp.s

src/matrix.o: src/matrix.cpp.o

.PHONY : src/matrix.o

# target to build an object file
src/matrix.cpp.o:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/src/matrix.cpp.o
.PHONY : src/matrix.cpp.o

src/matrix.i: src/matrix.cpp.i

.PHONY : src/matrix.i

# target to preprocess a source file
src/matrix.cpp.i:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/src/matrix.cpp.i
.PHONY : src/matrix.cpp.i

src/matrix.s: src/matrix.cpp.s

.PHONY : src/matrix.s

# target to generate assembly for a file
src/matrix.cpp.s:
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/src/matrix.cpp.s
.PHONY : src/matrix.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/test_library.dir/build.make CMakeFiles/test_library.dir/test/test.cpp.o
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/test_library.dir/build.make CMakeFiles/test_library.dir/test/test.cpp.i
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/test_library.dir/build.make CMakeFiles/test_library.dir/test/test.cpp.s
	$(MAKE) -f CMakeFiles/cmake_testing.dir/build.make CMakeFiles/cmake_testing.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test_library"
	@echo "... cmake_testing"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/calc.o"
	@echo "... src/calc.i"
	@echo "... src/calc.s"
	@echo "... src/matrix.o"
	@echo "... src/matrix.i"
	@echo "... src/matrix.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

